services:
  database:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: salainensalasana
      PGSSLMODE: disable
    volumes:
      - ./pgdata:/var/lib/postgresql
    container_name: postgres