POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJpaGhhcmRAbWFpbC5jb20iLCJpZCI6NywiaWF0IjoxNzc3NDA5ODkzfQ.DqFu0-Kc_NOQ-hwvbXp-uBsEzqUQGXkBWZx__-5V4yc

{
    "title": "Adding trash to be deleted",
    "author": "Weirdo",
    "url": "asdasd.com",
    "year": 2022
}
