DELETE http://localhost:3001/api/blogs/5
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJpaGhhcmRAbWFpbC5jb20iLCJpZCI6MSwiaWF0IjoxNzc3NDA2MzE0fQ.dojfqa2uMQRoGti8W8jYiv3V1Kun_Xeodh3Ic9g_ghM